---
- name: install xroad security server packages
  command: yum -y install xroad-securityserver-fi

- name: add xroad admin user
  command: "xroad-add-admin-user {{ xroad_ui_user }}"

- name: start xroad-proxy
  service:
    name: xroad-proxy
    state: started
