---
xroad_ui_user: "xrd"
xroad_ui_user_password: "$6$Esp64ze9owZGsfI5$s6Wx5diVppHi8AoAUKU6LACNHB7dky3Gc3g4Ewa3e/x8lCjgVswA2EcUVpF2l9IadOHooFFjtbBMNWZAO2Xg4/"
ubuntu_repo_url: "http://www.nic.funet.fi/pub/csc/x-road/client/ubuntu-prod-current/packages"
ubuntu_apt_key:  "{{ubuntu_repo_url}}/dists/stable/palveluvayla@gofore.com.asc"
ubuntu_apt_repo: "deb {{ubuntu_repo_url}} stable main"
