---
package_source: "remote"

ubuntu_14_apt_key:  "https://artifactory.niis.org/api/gpg/key/public"
ubuntu_14_repo_url: "https://artifactory.niis.org/xroad-release-deb"
ubuntu_14_apt_repo: "deb {{ubuntu_14_repo_url}} trusty-current main"

ubuntu_18_apt_key:  "https://s3-eu-west-1.amazonaws.com/niis-xroad-development/develop/jenkins%40niis.org.gpg"
ubuntu_18_repo_url: "https://s3-eu-west-1.amazonaws.com/niis-xroad-development/develop/debian"
ubuntu_18_apt_repo: "deb {{ubuntu_18_repo_url}} bionic main"

rhel_repo_baseurl: "https://artifactory.niis.org/xroad-release-rpm/rhel/7/current"
rhel_repo_gpgcheck: "yes"
rhel_repo_gpgkey: "https://artifactory.niis.org/api/gpg/key/public"
rhel_repo_repogpgcheck: "yes"
