
- name: Ready all Ubuntu 14.04 containers
  with_inventory_hostnames: all:!lxd-servers:!centos-ss
  lxd_container:
    name: "{{item}}"
    state: started
    source:
      type: image
      mode: pull
      server: https://cloud-images.ubuntu.com/releases
      protocol: simplestreams
      alias: "{{ ubuntu_releasever }}"
    profiles: ["default"]
    wait_for_ipv4_addresses: true
    timeout: 600

- name: Ready all CentOS 7 containers
  with_inventory_hostnames: centos-ss
  lxd_container:
    name: "{{item}}"
    state: started
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      protocol: lxd
      alias: centos/{{centos_releasever}}/amd64
    profiles: ["default"]
    wait_for_ipv4_addresses: true
    timeout: 600
