---
# This playbook compiles X-Road and installs the compiled packages to the defined host inventory

- hosts: lxd-servers
  roles:
    - init-lxd
  tags: 
    - init

- hosts: compile-servers
  roles:
    #- compile
    #- build-packages
  tags: 
    - compile

- hosts: ss-servers, cs-servers, cp-servers
  roles:
    - prepare_host
  tags:
    - init

- hosts: ss-servers, cs-servers, cp-servers
  roles:
    - packages-to-local-repo
  tags:
    - packages

- hosts: cs-servers
  become: yes
  become_user: root
  roles:
    - xroad-cs
  tags:
    - cs
    - install
    
- hosts: cp-servers
  become: yes
  become_user: root
  roles:
    - xroad-cp
  tags:
    - cp
    - install

- hosts: ca-servers
  become: yes
  become_user: root
  roles:
    - xroad-ca
  tags:
    - ca
    - install

- hosts: ss-servers
  become: yes
  become_user: root
  roles:
    - xroad-ss
  tags:
    - ss
    - install
  vars:
    #local package repository configuration for centos
    #xroad_repo_template: xroad-local.repo.j2
    #xroad_repo_dest: /etc/yum.repos.d/xroad-local.repo
    xroad_package_src: local
    xroad_repo_baseurl: file:///xroad/CentOS/$releasever/local
    xroad_repo_gpgcheck: no
    xroad_repo_gpgkey: http://www.nic.funet.fi/pub/csc/x-road/client/rhel7-prod-current/palveluvayla-sign.gpg
    xroad_repo_gpgcakey: http://www.nic.funet.fi/pub/csc/x-road/client/rhel7-prod-current/palveluvayla-ca.gpg
    xroad_repo_repogpgcheck: no