- name: show OS version
  debug:
    msg: "OS = {{ ansible_os_family }} "

- name: check that OS = Redhat
  fail:
    msg: "This playbook only supports Ubuntu"
  when: ansible_os_family != "Debian"

- name: Install git
  apt: name=git state=present

- stat:
    path: "{{ xroad_python_tests_local_path }}"
  register: dir
  
- stat:
    path: "{{ xroad_python_tests_local_path }}{{ xroad_python_tests_root }}"
  register: git_dir
  
- name: create local X-Road test directory
  file:
    path: "{{ xroad_python_tests_local_path }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0775
    recurse: yes
  when: dir.stat.exists == False

- name: download X-Road Python tests
  shell: git clone {{ xroad_python_tests_git_path }}
  args:
    chdir: "{{ xroad_python_tests_local_path }}"
  when: git_dir.stat.exists == False

