---
- name: Install required packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release
    - curl
    - createrepo
    - cronie
    - tar

- name: Create / update repo
  become: yes
  command: createrepo /xroad/CentOS/{{centos_releasever}}/local
  when: package_source == "local"
  args:
    chdir: /xroad/CentOS/{{centos_releasever}}/local
  tags: centos-repo

- name: Setup the correct repository for X-Road installation
  yum_repository:
    name: xroad-repository
    description: Repository for installing X-Road packages
    baseurl: "{{ rhel_repo_baseurl }}"
    gpgcheck: "{{ rhel_repo_gpgcheck }}"
    gpgkey: "{{ rhel_repo_gpgkey }}"
    gpgcakey: "{{ rhel_repo_gpgcakey }}"
    repo_gpgcheck: "{{ rhel_repo_gpgcheck }}"
    state: present
    enabled: yes
