---
- name: Update all packages to the latest version
  apt:
    force: yes
    upgrade: dist

- name: "update apt cache"
  apt:
    update_cache: yes

- name: ensure that acl utilities is installed
  # see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user
  package:
      name: acl
      state: present

- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - curl
    - apt-transport-https
    - apt-utils
    - net-tools

- name: install trusty apt repo key
  apt_key:
    url: "{{ubuntu_14_apt_key}}"
    state: present
  when: package_source == "remote" and ansible_distribution_release == 'trusty'

- name: install bionic apt repo key
  apt_key:
    url: "{{ubuntu_18_apt_key}}"
    state: present
  when: package_source == "remote" and ansible_distribution_release == 'bionic'

- name: xroad trusty apt repository
  apt_repository:
    repo: "{{ubuntu_14_apt_repo}}"
    state: present
  when: ansible_distribution_release == 'trusty'

- name: xroad bionic apt repository
  apt_repository:
    repo: "{{ubuntu_18_apt_repo}}"
    state: present
  when: ansible_distribution_release == 'bionic'

# ppa doesn't work with debian, only ubuntu
- name: openjdk and nginx repositories
  apt_repository:
    repo: "ppa:{{ item }}"
  with_items:
    - openjdk-r/ppa
    - nginx/stable

- name: enable UTF-8 locales
  lineinfile:
    line: "{{ item }}"
    dest: "/var/lib/locales/supported.d/local"
    state: present
    create: yes
  register: locale_added
  with_items:
    - "fi_FI.UTF-8 UTF-8"
    - "en_US.UTF-8 UTF-8"

- name: generate locales
  command: "/usr/sbin/locale-gen"
  when: locale_added.changed

- name: "update apt cache"
  apt:
    update_cache: yes
